import { redis } from './redis';

// Export all cache keys here for reuse
export const CACHE_KEYS = {
  /* ===================== BASIC LISTS ===================== */
  STOPS_LIST: process.env.STOPS_CACHE_KEY,
  TICKET_TYPES: process.env.TICKET_TYPES_LIST,
  DASHBOARD: process.env.DASHBOARD_CACHE_KEY,

  ROUTES: process.env.ROUTES_CACHE_KEY,
  ROUTES_FULL: process.env.ROUTES_FULL_CACHE_KEY,

  BUS_ASSIGNMENTS: process.env.BUS_ASSIGNMENTS_CACHE_KEY,

  /* ===================== BUS OPERATIONS ===================== */
  BUS_OPERATIONS_ALL: process.env.BUS_OPERATIONS_CACHE_KEY_ALL,
  BUS_OPERATIONS_NOTREADY: process.env.BUS_OPERATIONS_CACHE_KEY_NOTREADY,
  BUS_OPERATIONS_NOTSTARTED: process.env.BUS_OPERATIONS_CACHE_KEY_NOTSTARTED,
  BUS_OPERATIONS_INOPERATION: process.env.BUS_OPERATIONS_CACHE_KEY_INOPERATION,

  /* ===================== DAMAGE REPORTS ===================== */
  DAMAGE_REPORT_ALL: process.env.DAMAGE_REPORT_CACHE_KEY_ALL,
  DAMAGE_REPORT_PENDING: process.env.DAMAGE_REPORT_CACHE_KEY_PENDING,
  DAMAGE_REPORT_ACCEPTED: process.env.DAMAGE_REPORT_CACHE_KEY_ACCEPTED,
  DAMAGE_REPORT_REJECTED: process.env.DAMAGE_REPORT_CACHE_KEY_REJECTED,
  DAMAGE_REPORT_NA: process.env.DAMAGE_REPORT_CACHE_KEY_NA,

  /* ===================== MAINTENANCE WORK (STATUS ONLY) ===================== */
  MAINTENANCE_ALL: process.env.MAINTENANCE_WORK_CACHE_KEY_STATUS_All,
  MAINTENANCE_PENDING: process.env.MAINTENANCE_WORK_CACHE_KEY_STATUS_Pending,
  MAINTENANCE_INPROGRESS: process.env.MAINTENANCE_WORK_CACHE_KEY_STATUS_InProgress,
  MAINTENANCE_COMPLETED: process.env.MAINTENANCE_WORK_CACHE_KEY_STATUS_Completed,
  MAINTENANCE_CANCELLED: process.env.MAINTENANCE_WORK_CACHE_KEY_STATUS_Cancelled,

  MAINTENANCE_LOW: process.env.MAINTENANCE_WORK_CACHE_KEY_STATUS_Low,
  MAINTENANCE_MEDIUM: process.env.MAINTENANCE_WORK_CACHE_KEY_STATUS_Medium,
  MAINTENANCE_HIGH: process.env.MAINTENANCE_WORK_CACHE_KEY_STATUS_High,
  MAINTENANCE_CRITICAL: process.env.MAINTENANCE_WORK_CACHE_KEY_STATUS_Critical,

  /* ===================== MAINTENANCE WORK (STATUS + PRIORITY) ===================== */
  MAINTENANCE_PENDING_LOW: process.env.MAINTENANCE_WORK_CACHE_KEY_STATUS_Pending_Low,
  MAINTENANCE_PENDING_MEDIUM: process.env.MAINTENANCE_WORK_CACHE_KEY_STATUS_Pending_Medium,
  MAINTENANCE_PENDING_HIGH: process.env.MAINTENANCE_WORK_CACHE_KEY_STATUS_Pending_High,
  MAINTENANCE_PENDING_CRITICAL: process.env.MAINTENANCE_WORK_CACHE_KEY_STATUS_Pending_Critical,

  MAINTENANCE_INPROGRESS_LOW: process.env.MAINTENANCE_WORK_CACHE_KEY_STATUS_InProgress_Low,
  MAINTENANCE_INPROGRESS_MEDIUM: process.env.MAINTENANCE_WORK_CACHE_KEY_STATUS_InProgress_Medium,
  MAINTENANCE_INPROGRESS_HIGH: process.env.MAINTENANCE_WORK_CACHE_KEY_STATUS_InProgress_High,
  MAINTENANCE_INPROGRESS_CRITICAL: process.env.MAINTENANCE_WORK_CACHE_KEY_STATUS_InProgress_Critical,

  MAINTENANCE_COMPLETED_LOW: process.env.MAINTENANCE_WORK_CACHE_KEY_STATUS_Completed_Low,
  MAINTENANCE_COMPLETED_MEDIUM: process.env.MAINTENANCE_WORK_CACHE_KEY_STATUS_Completed_Medium,
  MAINTENANCE_COMPLETED_HIGH: process.env.MAINTENANCE_WORK_CACHE_KEY_STATUS_Completed_High,
  MAINTENANCE_COMPLETED_CRITICAL: process.env.MAINTENANCE_WORK_CACHE_KEY_STATUS_Completed_Critical,

  MAINTENANCE_CANCELLED_LOW: process.env.MAINTENANCE_WORK_CACHE_KEY_STATUS_Cancelled_Low,
  MAINTENANCE_CANCELLED_MEDIUM: process.env.MAINTENANCE_WORK_CACHE_KEY_STATUS_Cancelled_Medium,
  MAINTENANCE_CANCELLED_HIGH: process.env.MAINTENANCE_WORK_CACHE_KEY_STATUS_Cancelled_High,
  MAINTENANCE_CANCELLED_CRITICAL: process.env.MAINTENANCE_WORK_CACHE_KEY_STATUS_Cancelled_Critical,

  /* ===================== TASK MANAGEMENT ===================== */
  TASK_ALL: process.env.TASK_MANAGEMENT_CACHE_KEY_STATUS_All,
  TASK_PENDING: process.env.TASK_MANAGEMENT_CACHE_KEY_STATUS_Pending,
  TASK_INPROGRESS: process.env.TASK_MANAGEMENT_CACHE_KEY_STATUS_InProgress,
  TASK_COMPLETED: process.env.TASK_MANAGEMENT_CACHE_KEY_STATUS_Completed,
  TASK_CANCELLED: process.env.TASK_MANAGEMENT_CACHE_KEY_STATUS_Cancelled,

  TASK_LOW: process.env.TASK_MANAGEMENT_CACHE_KEY_STATUS_Low,
  TASK_MEDIUM: process.env.TASK_MANAGEMENT_CACHE_KEY_STATUS_Medium,
  TASK_HIGH: process.env.TASK_MANAGEMENT_CACHE_KEY_STATUS_High,
  TASK_CRITICAL: process.env.TASK_MANAGEMENT_CACHE_KEY_STATUS_Critical,

  TASK_PENDING_LOW: process.env.TASK_MANAGEMENT_CACHE_KEY_STATUS_Pending_Low,
  TASK_PENDING_MEDIUM: process.env.TASK_MANAGEMENT_CACHE_KEY_STATUS_Pending_Medium,
  TASK_PENDING_HIGH: process.env.TASK_MANAGEMENT_CACHE_KEY_STATUS_Pending_High,
  TASK_PENDING_CRITICAL: process.env.TASK_MANAGEMENT_CACHE_KEY_STATUS_Pending_Critical,

  TASK_INPROGRESS_LOW: process.env.TASK_MANAGEMENT_CACHE_KEY_STATUS_InProgress_Low,
  TASK_INPROGRESS_MEDIUM: process.env.TASK_MANAGEMENT_CACHE_KEY_STATUS_InProgress_Medium,
  TASK_INPROGRESS_HIGH: process.env.TASK_MANAGEMENT_CACHE_KEY_STATUS_InProgress_High,
  TASK_INPROGRESS_CRITICAL: process.env.TASK_MANAGEMENT_CACHE_KEY_STATUS_InProgress_Critical,

  TASK_COMPLETED_LOW: process.env.TASK_MANAGEMENT_CACHE_KEY_STATUS_Completed_Low,
  TASK_COMPLETED_MEDIUM: process.env.TASK_MANAGEMENT_CACHE_KEY_STATUS_Completed_Medium,
  TASK_COMPLETED_HIGH: process.env.TASK_MANAGEMENT_CACHE_KEY_STATUS_Completed_High,
  TASK_COMPLETED_CRITICAL: process.env.TASK_MANAGEMENT_CACHE_KEY_STATUS_Completed_Critical,

  TASK_CANCELLED_LOW: process.env.TASK_MANAGEMENT_CACHE_KEY_STATUS_Cancelled_Low,
  TASK_CANCELLED_MEDIUM: process.env.TASK_MANAGEMENT_CACHE_KEY_STATUS_Cancelled_Medium,
  TASK_CANCELLED_HIGH: process.env.TASK_MANAGEMENT_CACHE_KEY_STATUS_Cancelled_High,
  TASK_CANCELLED_CRITICAL: process.env.TASK_MANAGEMENT_CACHE_KEY_STATUS_Cancelled_Critical,

  /* ===================== RENTAL REQUESTS ===================== */
  RENTAL_REQUESTS_ALL: process.env.RENTAL_REQUEST_CACHE_KEY_ALL,
  RENTAL_REQUESTS_PENDING: process.env.RENTAL_REQUEST_CACHE_KEY_PENDING,
  RENTAL_REQUESTS_APPROVED: process.env.RENTAL_REQUEST_CACHE_KEY_APPROVED,
  RENTAL_REQUESTS_REJECTED: process.env.RENTAL_REQUEST_CACHE_KEY_REJECTED,
  RENTAL_REQUESTS_COMPLETED: process.env.RENTAL_REQUEST_CACHE_KEY_COMPLETED,
};

export async function getCache<T = any>(key: string): Promise<T | null> {
  const cached = await redis.get(key);
  if (!cached) return null;
  try {
    return (typeof cached === 'string' ? JSON.parse(cached) : cached) as T;
  } catch {
    await redis.del(key);
    return null;
  }
}

export async function setCache(key: string, value: any, ttlSeconds: number = 3600) {
  await redis.set(key, JSON.stringify(value), { ex: ttlSeconds });
}

export async function delCache(key: string) {
  await redis.del(key);
}

export async function clearAllCache() {
  await redis.flushdb();
}

